### ISSUE TITLE
Filteren op zaakid in Ladybug test tool

### ISSUE THREAD

**Issue by SWFTessavdLaan** [Sudwest-Fryslan/OpenZaakBrug#100]
In de ladybug tool staat de logging van de berichten van de OpenZaakbrug. Nu gaan hier veel berichten doorheen. 
Graag zou ik hier (snel) op het kenmerk zaakidentificatie willen zoeken. 
Dat scheelt behoorlijk in het zoeken naar het juiste bericht.

**Comment by EduardWitteveen** [comment]
Based upon xpath or java you can specify to look into messages, this can add an addtional column.
--> columname : xpath to Jaco

**Comment by EduardWitteveen** [comment]
duplicate van #103
