### ISSUE TITLE
How to deal with versioning

### ISSUE THREAD

**Issue by jacodg** [Sudwest-Fryslan/OpenZaakBrug#109]
We have a version in the pom.xml

We probably want the version tagged in Git

We want the Docker image to have a version so we can roll back to a previous version in P

Do we create tags afterwards? Or do we change the version in the pom.xml and is everything versioned automatically by CI/CD?

**Comment by EduardWitteveen** [comment]
https://blog.container-solutions.com/tagging-docker-images-the-right-way has also some nice comments

**Comment by EduardWitteveen** [comment]
We have a working sollution, closed by #294
