### ISSUE TITLE
Volgnummer bij status op 'niet leidend' 

### ISSUE THREAD

**Issue by SWFTessavdLaan** [Sudwest-Fryslan/OpenZaakBrug#18]
De volgnummers bij de statustypes veroorzaken op dit moment foutmeldingen, zoals: ...haarlem.tra......: zaakstatus verschil in omschrijving met volgnummer #4 verwacht: 'Afgehandeld' gekregen: 'Voorstel voor besluitvorming opgesteld'. 

Open zaak kent de volgende statustypes: 
1.         Ontvangen
2.         Geaccepteerd
3.         In behandeling genomen
4.         Afgehandeld
5.         Onderzoek afgerond
6.         Voorstel voor besluitvorming opgesteld
7.         Besluitvorming afgerond
8.         Ingetrokken

Deze volgnummers zijn leidend en dit is voor ons ongewenst. 
Het is niet werkbaar om altijd dit lijstje te volgen en daarbij maken wij gebruik van de zaaktypes, zoals omschreven in de I-navigator.

Daarom graag de volgnummers niet-leidend maken en de zaakstatus/omschrijving over te nemen, zoals in het bericht staat. 
  
 <omschrijving>...haarlem.tra......: zaakstatus verschil in omschrijving met volgnummer #4 verwacht: 'Afgehandeld' gekregen: 'Onderzoek afgerond'</omschrijving>
     <ZKN:gerelateerde StUF:entiteittype="STT" StUF:verwerkingssoort="T">
      <ZKN:zkt.code>B1026</ZKN:zkt.code>
      <ZKN:zkt.omschrijving>Aanvraag minima</ZKN:zkt.omschrijving>
      **<ZKN:volgnummer>0004</ZKN:volgnummer>**
      <ZKN:code>6</ZKN:code>
      <ZKN:omschrijving>Voorstel voor besluitvorming opgesteld</ZKN:omschrijving>

**Comment by EduardWitteveen** [comment]
Ik ga er vanuit dat het een stuk xml zoals het volgende betreft
```
               <ZKN:gerelateerde StUF:entiteittype="STT" StUF:verwerkingssoort="T">
                  <ZKN:zkt.code>B1026</ZKN:zkt.code>
                  <ZKN:zkt.omschrijving>Aanvraag minima</ZKN:zkt.omschrijving>
                  <ZKN:volgnummer>0002</ZKN:volgnummer>
                  <ZKN:code>Inbeh</ZKN:code>
                  <ZKN:omschrijving>In behandeling</ZKN:omschrijving>
                  <ZKN:ingangsdatumObject xsi:nil="true" StUF:noValue="geenWaarde"/>
               </ZKN:gerelateerde>
```
Op dit moment is der werking dat er wordt gekeken naar de inhoud van het element: <ZKN:omschrijving> en deze gematched wordt op het begin van Statustype.Omschrijving in ZGW. Wanneer het Statustype.volgnummer is gevuld in ZGW, wordt hier niets mee gedaan tov. het <ZKN:volgnummer> in ZDS, behalve een waarschuwing in de log, dat deze niet overeenkomstig zijn.
Kortom, in bestaande implementaties wordt er niet veel naar de volgnummers gekeken, het afdwingen geeft onwerkbaar gedrag.(dit is eerder al als een bug aangedragen en opgelost)

Het meest mooie zou zijn wanneer in ZGW het Statustype ook een Statustype.identificatie zou hebben (net als het zaaktype.identificatie , dan kan deze gebruikt worden om naar te refereren.  Wanneer dit toch gewenst is, kan dit aangemeld worden bij https://github.com/open-zaak/open-zaak , maar open-zaak zal waarschijnlijk het antwoord geven dat dit in de ZGW standaard zo gedefinieerd is.

Dus dan moet er een aanpassingen komen op de ZGW standaard: https://github.com/VNG-Realisatie/gemma-zaken .
Ik denk dat het wel goed is om een onderbouwing aan te geven voor waarom dit veld dan mee moet komen, want het argument dat het in de iNavigator staat is wel smal. Dit is de standaard, het iNavigator is een product.
