### ISSUE TITLE
Status en referenten

### ISSUE THREAD

**Issue by JohnRooijakkers** [Sudwest-Fryslan/OpenZaakBrug#224]
@EduardWitteveen of @haarlem-dvh, wat is de huidige status van de OpenZaakBrug en bij welke gemeenten en welke ZS-DMS systemen wordt deze (productief) gebruikt?

**Comment by EduardWitteveen** [comment]
@JohnRooijakkers De huidige status van Open Zaakbrug is dat wij, de gemeente Súdwest-Fryslân, live zijn.

Onze vergunning-zaken met Open Zaakbrug gemigreerd hebben vanuit het oude zds-zaaksysteem naar OpenZaak. 
Verder zijn de vakapplicaties van burgerzaken en vergunningen nu aangesloten op Open Zaakbrug, kortom onze medewerkers gebruiken het volop. Later dit jaar zullen we de applicaties uit het kcc en sociaaldomein ook overzetten, dan zijn we volledig over.

Lees ook meer op: https://commonground.nl/blog/view/6a946c44-851a-4a2b-bfaf-8368d886aff7/sudwest-fryslan-live-met-openzaak-en-open-zaakbrug
