### ISSUE TITLE
Aanpassen fout naar warning, bij titel niet gevuld

### ISSUE THREAD

**Issue by SWFTessavdLaan** [Sudwest-Fryslan/OpenZaakBrug#329]
Wanneer een titel niet gevuld is, bij een document, krijg ik de foutmelding: "name":"titel","code":"blank","reason":"Dit veld mag niet leeg zijn."}]}".
Dit wil ik niet als een fout zien in de OZB, maar als een warning.

**Comment by EduardWitteveen** [comment]
Filename gebruiken als titel bij ontbreken van de titel
