### ISSUE TITLE
Resultaat toekennen aan afgehandelde zaak B1647 

### ISSUE THREAD

**Issue by SWFTessavdLaan** [Sudwest-Fryslan/OpenZaakBrug#331]
In de openzaakbrug zien we de volgende fout: 

POST naar OpenZaak: https://.../zgw/zaken/api/v1/statussen gaf foutmelding:org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"type":"https://...../zgw/ref/fouten/ValidationError/","code":"invalid","title":"Invalid input.","status":400,"detail":"","instance":"urn:uuid:e89ca161-af85-4baa-9823-cd8223a1fb4e","invalidParams":[{"name":"nonFieldErrors",**"code":"resultaat-does-not-exist","reason":"Zaak has no resultaat."}]}"**

Dit vindt plaats bij de volgende actie: Update Zaak

Deze fout zien we bij zaken, met zaaktype: B1647. De zaak wordt afgesloten, maar er wordt geen resultaat mee gestuurd. Alleen een status afgehandeld en een einddatum. 
Wanneer de status afgehandeld is en een einddatum bekend is, dan moet de zaak afgesloten worden met resultaat; 'Afgehandeld'.

Waarschijnlijk is dit voor de B1646 al ingericht, hier moet hetzelfde gelden voor de B1647.

**Comment by EduardWitteveen** [comment]
Dit issue hoort bij de inrichting van swf, niet bij algemene OZB :-)
