### ISSUE TITLE
else if-statements bevatten dezelfde conditie

### ISSUE THREAD

**Issue by joostvanderborg** [Sudwest-Fryslan/OpenZaakBrug#351]
De conditie op regel [636](https://github.com/Sudwest-Fryslan/OpenZaakBrug/blob/6011ceb14b7e1311185ed39b70d3bf92e50f8143/src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java#LL636C11-L636C11) kan nooit waar zijn, omdat in regel [626](https://github.com/Sudwest-Fryslan/OpenZaakBrug/blob/6011ceb14b7e1311185ed39b70d3bf92e50f8143/src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java#L626) dezelfde conditie-check bestaat. Daardoor zal `zgwRol.betrokkeneIdentificatie.innRechtsvorm` nooit de waarde `naamloze_vennootschap` kunnen krijgen.

https://github.com/Sudwest-Fryslan/OpenZaakBrug/blob/6011ceb14b7e1311185ed39b70d3bf92e50f8143/src/main/java/nl/haarlem/translations/zdstozgw/translation/zds/services/ZaakService.java#LL636C11-L636C11

**Comment by jacodg** [comment]
Goed punt. Ik weet zelf niet direct welke string er in de if gebruikt zou moeten worden om onderscheid te maken tussen beide of dat er eentje weg kan maar ik zal het "in de groep gooien"

**Comment by haarlem-dvh** [comment]
Dit is inderdaad een bug. Er zijn meerdere mogelijke rechtsvormen die 'vennootschap' bevatten en dus altijd binnen 626 zullen vallen.

https://www.gemmaonline.nl/index.php/Rsgb_3.0/doc/enumeration/soortrechtsvorm
