### ISSUE TITLE
xmlns="" generated  with ladybug without net.sf.saxon

### ISSUE THREAD

**Issue by EduardWitteveen** [Sudwest-Fryslan/OpenZaakBrug#61]
While preparing the integration of Ladybug, the following strange behaviour occurs
- Without Ladybug without net.sf.saxon when 09-zds-updateZaak_Lk01 is run <stuurgegevens> 
- With Ladybug without net.sf.saxon when 09-zds-updateZaak_Lk01 is run <stuurgegevens xmlns=""> 
- With Ladybug with net.sf.saxon when 09-zds-updateZaak_Lk01 is run <stuurgegevens> 

When the source can not be located, we agreed that net.sf.saxon should be added as dependency, but if possible we want to know what is causing the problem.

**Comment by jacodg** [comment]
Copy of an email I've sent (sorry for using Dutch):

Het blijkt te komen door de volgende regel in XmlUtils.java:

Transformer transformer = TransformerFactory.newInstance().newTransformer();

Ik heb wat testjes gedaan met de volgende system out:

System.out.println(transformer.getClass().getCanonicalName());

Zonder Ladybug:
com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl
<stuurgegevens>

Alleen Ladybug toevoegen (zonder exclusions en ander dependencies):
net.sf.saxon.IdentityTransformer
<stuurgegevens xmlns="">

Als ik Saxon-HE als extra dependency toevoeg:
org.apache.xalan.transformer.TransformerIdentityImpl
<stuurgegevens>

Als ik Saxon-HE exclude bij ladybug:
java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl

Als ik Saxon-HE als dependency toevoeg en ibis-xerces en dom4j exclude bij Ladybug:
org.apache.xalan.transformer.TransformerIdentityImpl
<stuurgegevens>

Als ik Saxon-HE als dependency toevoeg en ibis-xerces, dom4j en xalan exclude bij Ladybug:
net.sf.saxon.IdentityTransformer
<stuurgegevens xmlns="">

Beetje vaag allemaal (bijvoorbeeld dat als je Saxon-HE als extra dependency toevoegt hij juist Xalan gaat gebruiken) maar ik vermoed dat het te maken heeft met welke jar uit de dependency ljist als eerste wordt gebruikt en daarvan de META-INF/services/javax.xml.transform.TransformerFactory. Maar goed, heeft niet zoveel zin om dat helemaal uit te pluizen. Oplossing is om expliciet Xalan te gebruiken (er wordt naar het aanmaken van de transformer ook een Xalan specifieke setOutputProperty op de tranformer gedaan) en het niet over te laten aan de “willekeur” van de dependencies, dus ik wil er dit van maken:

// Explicitly use Xalan to prevent Saxon-HE being used (depending on (transitive) dependencies in pom.xml).
// Saxon-HE is causing some of the SOAP response messages to become invalid by adding xmlns="".
Transformer transformer = new org.apache.xalan.processor.TransformerFactoryImpl().newTransformer();
