### ISSUE TITLE
Do we need to add the EUPL license in every header and source file?

### ISSUE THREAD

**Issue by EduardWitteveen** [Sudwest-Fryslan/OpenZaakBrug#67]

**Comment by EduardWitteveen** [comment]
een officieel document gevonden waarin advies staat staat hoe de EUPL gebruikt kan worden. Eén kopie van de hele license en daar in een korte header boven elke file naar verwijzen. Zie p15 en p16 in https://joinup.ec.europa.eu/sites/default/files/inline-files/EUPL%201_1%20Guidelines%20EN%20Joinup.pdf

**Comment by EduardWitteveen** [comment]
After reading this, i would expect that we have to add something like the following part to all sourcefiles:

```
/*
 * Copyright 2020-2021 The Open Zaakbrug Contributors
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the 
 * European Commission - subsequent versions of the EUPL (the "Licence");
 * 
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl5
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 */
```

**Comment by Oszilloraptor** [comment]
Hi @EduardWitteveen,

The url does not work (anymore?)

If you remove the 5 it will link to the newest version of the license: https://joinup.ec.europa.eu/software/page/eupl

SIncerely,
someone who stumbled randomly across this issue while searching for a license header to copy
