### ISSUE TITLE
Rollen zoals de i-navigator

### ISSUE THREAD

**Issue by SWFTessavdLaan** [Sudwest-Fryslan/OpenZaakBrug#8]
Het lukt op dit moment niet om een zaak aan te maken, omdat de rol 'Betrekking' niet toegevoegd is aan het ZTC. 
Dan onstaant de foutmelding: 
 <faultstring>Geen roltype niet gevonden ZTC voor identificatie: 'Betrekking</faultstring>

Op dit moment moet een zaaktype bestaan uit de volgende rollen: 
•	Betrekking
•	Belanghebbende
•	Initiator
•	Uitvoerende
•	Verantwoordelijke

Graag willen we hier zoveel mogelijk de standaard van de I-navigator gebruiken.
Dus dat de Roltypen hand in hand  gaan met de generieke omschrijvingen.

**Voorstel:** 
**Omschrijving**                 **Omschrijving generiek**               
Belanghebbende                Belanghebbende
Betrekking                          Behandelaar
Initiator                              Initiator
Uitvoerende                       Behandelaar
Verantwoordelijke              Beslisser

**Comment by EduardWitteveen** [comment]
Rollen zijn nu aanpasbaar systeembreed aanpasbaar in de configuratie, het bestand config.json
Hierin zijn de onderstaande rollen te benoemen, waarbij het eerste gedeelte aangeeft welk element uit Zds wordt gebruikt, de meegegeven waarde bepaald de Omschrijving van de Rol. 

De verdere inrichting van de roltype-definitie in openzaak mag naar wens worden aangepast.

```
	"zgwRolOmschrijving": {
		"heeftBetrekkingOp" : "BetrekkingOp",	
		"heeftAlsBelanghebbende": "Belanghebbende",
		"heeftAlsInitiator": "Initiator",
		"heeftAlsUitvoerende": "Uitvoerende",
		"heeftAlsVerantwoordelijke": "Verantwoordelijke",
		"heeftAlsGemachtigde": "Gemachtigde",
		"heeftAlsOverigBetrokkene": "OverigeBetrokkene"
	},
```
`
